web/urls.py
from django.contrib import admin
from django.urls import path
from webapp01 import views
from django.conf.urls.static import static
from django.conf.urls.static import static
from . import settings
 
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('index/', views.hello),
    path('user/add', views.user_add),
    path('user/login', views.user_login),
    path('test/insert',views.insert),
    path('',views.welcome),
    path('delete/',views.delete),
    path('rw_delete/',views.rw_delete),
    path('js_rw/',views.js_rw),
    path('login_success',views.login_success),
    path('task/add',views.task_add),
    path('task_detail/',views.task_detail),
    path('task/mytask',views.task_mytask),
    path('clear_session',views.clear_session),
    path('del_js_rw/',views.del_js_rw),
    path('wc_rw/',views.wc_rw),
    path('userinfo/',views.userinfo1),
    path('search1',views.search1),
]

webapp01/models.py
# models.py
from django.db import models


##用户id 用户账户 密码 手机号 年龄
class userinfo(models.Model):
    user_id = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=20)
    user_password = models.CharField(max_length=64)
    user_number = models.IntegerField()
    user_age = models.IntegerField(default=2)
##任务id 任务名称 发布用户id 发布用户名称 发布日期 截止日期 接收用户id 接收用户名称 接收日期 是否接取状态 是否为完成状态
class rw(models.Model):
    rw_id = models.AutoField(primary_key=True)
    rw_name = models.CharField(max_length=20)
    rw_context = models.CharField(max_length=40)
    rw_fb_userid = models.ForeignKey(userinfo,related_name='userinfo_fb_set',on_delete=models.CASCADE)
    rw_fb_username = models.CharField(max_length=20)
    rw_startdata = models.CharField(max_length=20)
    rw_enddata = models.CharField(max_length=20)
    rw_js_userid =  models.ForeignKey(userinfo, related_name='userinfo_js_set',on_delete=models.CASCADE,null=True)
    rw_js_username = models.CharField(max_length=20,null=True)
    rw_js_data = models.CharField(max_length=20,null=True)
    rw_js_state = models.BooleanField(default=False)
    rw_state = models.BooleanField(default=False)

webapp01/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from webapp01.models import userinfo,rw
from webapp01 import models
from django.db.models import Q
from django import forms
from datetime import datetime, timedelta
import hashlib
from django.contrib import messages
import sys

# 从命令行参数获取 IP 地址和端口号
if 'runserver' in sys.argv:
    try:
        runserver_index = sys.argv.index('runserver')
        ip, port = sys.argv[runserver_index + 1].split(':')
        # 将 IP 地址和端口号保存到全局变量中
        GLOBAL_IP = ip
        GLOBAL_PORT = port
    except (IndexError, ValueError):
        pass
def my_view():
    # 获取 IP 地址和端口号
    if len(sys.argv) > 2:
        ip_port = sys.argv[2]
        ip, port = ip_port.split(':')
        return (ip,port)
    else:
        return HttpResponse("IP and Port not specified")

class LoginForm(forms.Form):
    user_name=forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    user_password=forms.CharField(
        label="用户名",
        widget=forms.PasswordInput,
        required=True
    )
    error_login = ""
    error_password=""
    

# Create your views here.
def hello(request):
    return HttpResponse("Hello ")
##添加用户
def user_add(request):
    if request.method=="POST":
        form = LoginForm()
        if form.is_valid():
            user_name1 = request.POST.get('user_name')
            user_password1 = request.POST.get('user_password')
            user_number1 = request.POST.get('user_number')
            user_age1 = request.POST.get('user_age')
            username = userinfo.objects.filter(user_name=user_name1).first()
            if username is not None :
                if user_name1 == username.user_name :
                    form.error = "该用户名已被注册！"
                    return render(request,"user_add.html",{'form':form})
            else:
                userinfo.objects.create(user_name=user_name1,user_password=user_password1,user_number=user_number1,user_age=user_age1)
                redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}"
                return redirect(redirect_url)
            # return redirect("http://127.0.0.1:8000")
        else:
            form.error = "不能有空选项！"
            return render(request,"user_add.html",{'form':form})
    return render(request,"user_add.html")


##用户界面
def userinfo1(request):
    rw_list = userinfo.objects.all()
    return render(request,"userinfo.html",{'rw_list':rw_list})


##主页
def welcome(request):
    info = request.session.get('info')
    if not info:
        rw_list = rw.objects.filter(rw_js_state=False)
        login = False
        print(GLOBAL_IP,GLOBAL_PORT)
        return render(request,"welcome.html",{'rw_list':rw_list,'login':login,"GLOBAL_IP":GLOBAL_IP,"GLOBAL_PORT":GLOBAL_PORT})
    else:
        redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}/login_success"
        return redirect(redirect_url)
        # return redirect("http://127.0.0.1:8000/login_success")


def insert(request):
    user = models.userinfo.objects.create(user_name="wiair",user_password=123,user_number=123344)
    redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}/userinfo"
    return redirect(redirect_url)
    # return redirect("http://127.0.0.1:8000/userinfo")


##删除用户
def delete(request):
    user_id1 = request.GET.get('user_id')
    print(user_id1)
    models.userinfo.objects.filter(user_id = user_id1).delete()
    redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}/userinfo"
    return redirect(redirect_url)
    # return redirect("http://127.0.0.1:8000/userinfo")


##删除任务
def rw_delete(request):
    result = is_login(request)
    if result:
        return result
    rw_id1 = request.GET.get('rw_id')
    print(rw_id1)
    models.rw.objects.filter(rw_id = rw_id1).delete()
    redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}/task/mytask"
    return redirect(redirect_url)
    # return redirect("http://127.0.0.1:8000/task/mytask")



##md5加密
def clean_user_password(password):
        Encry = hashlib.md5()  # 实例化md5
        Encry.update(password.encode())  # 字符串字节加密
        md5_pwd = Encry.hexdigest() # 字符串加密
        return md5_pwd



##用户登录模块
def user_login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request,"user_login.html",{'form':form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        # yz = models.userinfo.objects.filter(user_name = form.cleaned_data['user_name'],user_password = form.cleaned_data['user_password']).first()
        #如果数据库字段一致可以用以下写法
        yz = models.userinfo.objects.filter(**form.cleaned_data).first()
        # print(form.cleaned_data['user_name'],clean_user_password(form.cleaned_data['user_password']))
        # print(yz)
        if not yz:
            form.error_password=("用户名或密码错误！")
            return render(request,"user_login.html",{'form':form})
        else:
            request.session["info"] = {'id':yz.user_id,'name':yz.user_name}
            # print(request.session["info"]['id'])
            # print(request.session["info"]['id'])
            rw_list1 = rw.objects.filter(rw_js_state = False)
            redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}/login_success"
            params = {'name1': request.session["info"], 'rw_list': rw_list1}
            return redirect(redirect_url, params)
            # return redirect()
    else:
        form.error_login=("不能为空!")
        form.error_password = ("不能为空!")
        return render(request,"user_login.html",{'form':form})
##判断是否为登录状态
def is_login(request):
    info = request.session.get('info')
    if not info:
        form = LoginForm()
        form.error_login = "请登录账号！"
        messages.error(request, form.error_login)  # 将错误信息存储到消息中
        return redirect('/user/login')

##登录成功页面
def login_success(request):
    ##是否为登录状态用法
    result = is_login(request)
    if result:
        return result
    rw_user = request.session.get('info')
    rw_list1 = rw.objects.filter(Q(rw_js_state = False) & Q(rw_state=False))
    return render(request,"login_success.html",{'name1':rw_user,'rw_list':rw_list1,"GLOBAL_IP":GLOBAL_IP,"GLOBAL_PORT":GLOBAL_PORT})

##添加任务页面
def task_add(request):
    result = is_login(request)
    if result:
        return result
    current_time = datetime.now()
    year = current_time.year
    month = current_time.month
    day = current_time.day
    hour = current_time.hour
    time1 = f"{year}年{month}月{day}日{hour}时"
    current_time2 = current_time + timedelta(days=1)
    year = current_time2.year
    month = current_time2.month
    day = current_time2.day
    hour = current_time2.hour
    time2 = f"{year}年{month}月{day}日{hour}时"

    if request.method=="POST":
        rw_user = request.session.get('info')
        rw_name1 = request.POST.get('rw_name')
        rw_context1 = request.POST.get('rw_context')
        rw_startdata1 = request.POST.get('rw_fb_startdata')
        rw_enddata1 = request.POST.get('rw_fb_enddata')
        rw.objects.create(
            rw_name=rw_name1,
            rw_fb_username=rw_user.get('name'),
            rw_fb_userid_id=rw_user.get('id'),
            rw_startdata=rw_startdata1,
            rw_enddata=rw_enddata1,
            rw_context=rw_context1,
            )
        redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}/login_success"
        return redirect(redirect_url)
    return render(request,"task_add.html",{"time1":time1,"time2":time2})
##我的任务页面
def task_mytask(request):
    result = is_login(request)
    if result:
        return result
    rw_user = request.session.get('info')
    rw_fb_username1=rw_user.get('name'),
    rw_list1 = rw.objects.filter(rw_fb_username=rw_fb_username1[0])
    rw_list2 = rw.objects.filter(Q(rw_js_username=rw_fb_username1[0]) & Q(rw_state=False))
    return render(request,"task_mytask.html",{'rw_list':rw_list1,'rw_jslist':rw_list2,"GLOBAL_IP":GLOBAL_IP,"GLOBAL_PORT":GLOBAL_PORT})
##任务详情页
def task_detail(request):
    rw_id1 = request.GET.get('rw_id')
    login1 = request.GET.get('login')
    print(login1)
    rw1 = rw.objects.filter(rw_id=rw_id1)
    return render(request,"task_detail.html",{"rw_detail":rw1,"login":login1,"GLOBAL_IP":GLOBAL_IP,"GLOBAL_PORT":GLOBAL_PORT})
##注销
def clear_session(request):
    request.session.clear()
    redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}"
    return redirect(redirect_url)
##接收任务
def js_rw(request):
    result = is_login(request)
    if result:
        return result
    rw_id1 = request.GET.get('rw_id')
    rw.objects.filter(rw_id = rw_id1).update(rw_js_state = "True")
    rw_user = request.session.get('info')
    rw_js_username1=rw_user.get('name')
    rw_js_userid1=rw_user.get('id')
    current_time = datetime.now()
    year = current_time.year
    month = current_time.month
    day = current_time.day
    hour = current_time.hour
    rw_js_data1 = f"{year}年{month}月{day}日{hour}时"
    rw.objects.filter(rw_id = rw_id1).update(
        rw_js_userid_id = rw_js_userid1,
        rw_js_username = rw_js_username1,
        rw_js_data = rw_js_data1,
    )
    # +类.objects.create(+列="内容")
    ##+类.objects.filter(+列="内容"(查找的内容)).update("修改的内容")
    redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}/login_success"
    return redirect(redirect_url)
##删除接收任务
def del_js_rw(request):
    result = is_login(request)
    if result:
        return result
    rw_id1 = request.GET.get('rw_id')
    rw_js_username1=None
    rw_js_userid1=None
    rw_js_data1 =None
    rw.objects.filter(rw_id = rw_id1).update(rw_js_state = "False")
    rw.objects.filter(rw_id = rw_id1).update(
        rw_js_userid_id = rw_js_userid1,
        rw_js_username = rw_js_username1,
        rw_js_data = rw_js_data1,
    )
    rw_user = request.session.get('info')
    rw_fb_username1=rw_user.get('name'),
    rw_list1 = rw.objects.filter(rw_fb_username=rw_fb_username1[0])
    rw_list2 = rw.objects.filter(rw_js_username=rw_fb_username1[0])
    redirect_url = f"http://{GLOBAL_IP}:{GLOBAL_PORT}/task/mytask"
    params = {'rw_list': rw_list1,'rw_jslist':rw_list2}

webapp01/templates/login_success.html
{% load static %}
<!DOCTYPE html>
 <meta http-equiv="Cache-Control" content="max-age=7200" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>

<body>
    <h1 align="center">主页</h1>
        
    <div class="searchmain">
        <div class="searchcontainer">
            <form action="search1" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="搜索" class="search" name="search"><input type="submit" class="btnsearch" value="搜索">
        </div>
        <div class="login">
            <div>欢迎，{{name1.name}}</div>
            <a class="niceButton3" href="/task/add">发布任务</a>
            <a class="niceButton3" href="/task/mytask">我的任务</a>     
            <a class="niceButton3" href="/clear_session">注销</a>
        </div>
    </div>
    
    <table>
    <thead>
        <tr>
          <th>任务名称</th>
          <th>发布者</th>
          <th>发布日期</th>
          <th>截止日期</th>
          <th>操作</th>
        </tr>
    </thead>
            {% for i in rw_list%}
                <tr>
                <td>{{i.rw_name}}</td>
                <td>{{i.rw_fb_username}}</td>
                <td>{{i.rw_startdata}}</td>
                <td>{{i.rw_enddata}}</td>
                <td>
                <a class="niceButton2"href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/task_detail/?rw_id={{i.rw_id}}" style="text-decoration: none;">详情</a>
                <a class="niceButton2"href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/js_rw/?rw_id={{i.rw_id}}" style="text-decoration: none;">接受</a>
                </td>
                </tr>
            {% endfor %} 
    </table>
</body>
</html>

webapp01/templates/search1.html
{% load static %}
<!DOCTYPE html>
 <meta http-equiv="Cache-Control" content="max-age=7200" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>
<body>
<h1 style="display: flex; justify-content: center; align-items: center; height: 50px;">“{{search}}”的搜索结果</h1>
<div style="margin-left: auto; margin-right: 0; width: 10%;">
{% if login %}
<a href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/login_success" class="niceButton3" >返回任务列表</a>
{% else %}
<a href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}" class="niceButton3" >返回任务列表</a>
{% endif %}
</div>
 <table>
    <thead>
        <tr>
          <th>任务名称</th>
          <th>任务内容</th>
          <th>发布者</th>
          <th>发布日期</th>
          <th>截止日期</th>
          <th>接收者</th>
          <th>接收日期</th>
          <th>是否被接取</th>
          <th>是否完成任务</th>
        </tr>
    </thead>
            {% for i in rw_search%}
                <tr>
                <td>{{i.rw_name}}</td>
                <td>{{i.rw_context}}</td>
                <td>{{i.rw_fb_username}}</td>
                <td>{{i.rw_startdata}}</td>
                <td>{{i.rw_enddata}}</td>
                <td>{{i.rw_js_username|default_if_none:""}}</td>
                <td>{{i.rw_js_data|default_if_none:""}}</td>
                <td>{% if i.rw_js_state %}是{% else %}否{% endif %}</td>
                <td>{% if i.rw_state %}是{% else %}否{% endif %}</td>
                </tr>
            {% endfor %} 
             {% for i in user_search%}
                <tr>
                <td>{{i.rw_name}}</td>
                <td>{{i.rw_context}}</td>
                <td>{{i.rw_fb_username}}</td>
                <td>{{i.rw_startdata}}</td>
                <td>{{i.rw_enddata}}</td>
                <td>{{i.rw_js_username|default_if_none:""}}</td>
                <td>{{i.rw_js_data|default_if_none:""}}</td>
                <td>{% if i.rw_js_state %}是{% else %}否{% endif %}</td>
                <td>{% if i.rw_state %}是{% else %}否{% endif %}</td>
                </tr>
            {% endfor %} 
    </table>
</body>
</html>

webapp01/templates/task_add.html
{% load static %}
<!DOCTYPE html>
 <meta http-equiv="Cache-Control" content="max-age=7200" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>
<body class="login-body">
<div class="login-container">
<h1>添加任务</h1>
<form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
        <label for="rw_name">任务名称：</label>
        <input type="text" name="rw_name">
        <label for="rw_context">任务内容：</label>
        <input type="text" name="rw_context">
        <label for="rw_fb_startdata">发布日期：</label>
        <input type="text" name="rw_fb_startdata" value="{{time1}}"  placeholder="{{time1}}">
        <label for="rw_fb_enddata">截止日期：</label>
        <input type="text"name="rw_fb_enddata" value="{{time2}}" placeholder="{{time2}}" >
        <input type="submit" value="发布">
    </form>
</body>
</div>
</html>

webapp01/templates/task_detail.html
{% load static %}
<!DOCTYPE html>
 <meta http-equiv="Cache-Control" content="max-age=7200" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>
<body>
<h1 style="display: flex; justify-content: center; align-items: center; height: 50px;">任务详情</h1>
<div style="margin-left: auto; margin-right: 0; width: 10%;">
{% if login %}
<a href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}" class="niceButton3" >返回任务列表</a>
{% else %}
<a href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/login_success" class="niceButton3" >返回任务列表</a>
{% endif %}
</div>
 <table>
    <thead>
        <tr>
          <th>任务名称</th>
          <th>任务内容</th>
          <th>发布者</th>
          <th>发布日期</th>
          <th>截止日期</th>
          <th>接收者</th>
          <th>接收日期</th>
          <th>是否被接取</th>
          <th>是否完成任务</th>
        </tr>
    </thead>
            {% for i in rw_detail%}
                <tr>
                <td>{{i.rw_name}}</td>
                <td>{{i.rw_context}}</td>
                <td>{{i.rw_fb_username}}</td>
                <td>{{i.rw_startdata}}</td>
                <td>{{i.rw_enddata}}</td>
                <td>{{i.rw_js_username|default_if_none:""}}</td>
                <td>{{i.rw_js_data|default_if_none:""}}</td>
                <td>{% if i.rw_js_state %}是{% else %}否{% endif %}</td>
                <td>{% if i.rw_state %}是{% else %}否{% endif %}</td>
                </tr>
            {% endfor %} 
    </table>
</body>
</html>

webapp01/templates/task_mytask.html
{% load static %}
<!DOCTYPE html>
 <meta http-equiv="Cache-Control" content="max-age=7200" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>
<body>
<h1 style="display: flex; justify-content: center; align-items: center; height: 50px;">我发布的任务</h1>
<div style="margin-left: auto; margin-right: 0; width: 10%;">
<a href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/login_success" class="niceButton3" >返回任务列表</a>
</div>
 <table>
    <thead>
        <tr>
          <th>任务名称</th>
          <th>发布者</th>
          <th>发布日期</th>
          <th>截止日期</th>
          <th>操作</th>
          <th>任务完成状态</th>
        </tr>
    </thead>
            {% for i in rw_list%}
                <tr>
                <td>{{i.rw_name}}</td>
                <td>{{i.rw_fb_username}}</td>
                <td>{{i.rw_startdata}}</td>
                <td>{{i.rw_enddata}}</td>
                <td>
                <a class="niceButton2"href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/task_detail/?rw_id={{i.rw_id}}" style="text-decoration: none;">详情</a>
                <a class="niceButton2" href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/rw_delete/?rw_id={{i.rw_id}}" style="text-decoration: none;">删除</a>
                </td>
                <td>
                {% if i.rw_state %}
                    <div style="color:green;">√</div>
                {% else %}
                    <div style="color:red;">X</div>
                {% endif  %}
                </td>
                </tr>
            {% endfor %}
    </table>
<h1 style="display: flex; justify-content: center; align-items: center; height: 50px;">我接收的任务</h1>
<table>
    <thead>
        <tr>
          <th>任务名称</th>
          <th>发布者</th>
          <th>发布日期</th>
          <th>截止日期</th>
          <th>操作</th>
        </tr>
    </thead>
            {% for i in rw_jslist%}
                <tr>
                <td>{{i.rw_name}}</td>
                <td>{{i.rw_fb_username}}</td>
                <td>{{i.rw_startdata}}</td>
                <td>{{i.rw_enddata}}</td>
                <td>
                <a class="niceButton2"href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/task_detail/?rw_id={{i.rw_id}}" style="text-decoration: none;">详情</a>
                <a class="niceButton2" href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/del_js_rw/?rw_id={{i.rw_id}}" style="text-decoration: none;">删除</a>
                <a class="niceButton2" href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/wc_rw/?rw_id={{i.rw_id}}" style="text-decoration: none;">完成任务</a>                
                </td>
                </tr>
            {% endfor %} 
    </table>

</body>
</html>

webapp01/templates/user_add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <title>Document</title>
</head>
<body class="login-body">
    <div class="login-container">
    <h1>添加用户</h1>
    
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
                <label for="username">用户名：</label>
                <input type="text" id="username" name="user_name">
                <span style="color:red;" class="error">{{ form.error }}</span>
            </div>
            <div class="form-group">
                <label for="password">密码：</label>
                <input type="password" id="password" name="user_password">
            </div>
            <div class="form-group">
                <label for="phone">手机号：</label>
                <input type="text" id="phone" name="user_number">
            </div>
            <div class="form-group">
                <label for="age">年龄：</label>
                <input type="text" id="age" name="user_age">
            </div>
            <input type="submit" class="niceButton2" value="注册">
    </form>
</body>
</div>
</html>

webapp01/templates/user_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <title>login</title>
</head>
<body>
    <div class="login-container">
    <h1>用户登录</h1>
    <body class="login-body">
    <form action="" method="POST" novalidate>
        {% csrf_token %}
         <div class="form-group">
                <label for="id_user_name">用户名</label>
                {{ form.user_name }}
                <span class="error">{{ form.error_login }}</span>
            </div>
            <div class="form-group">
                <label for="id_user_password">密码</label>
                {{ form.user_password }}
                <span class="error">{{ form.error_password }}</span>
            </div>
            <input type="submit" value="登录">
        {% for message in messages %}
        <div class="error">{{ message }}</div>
    {% endfor %}
    </form>
</body>
</div>
</body>
</html>

webapp01/templates/userinfo.html
{% load static %}
<!DOCTYPE html>
 <meta http-equiv="Cache-Control" content="max-age=7200" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>

<body>
    <h1 align="center">主页</h1>
        
    <div class="searchmain">
        <div class="searchcontainer">
            <input type="text" placeholder="搜索" class="search">
            <button class="btnsearch">搜索</button>
        </div>
        <div class="login">
            <a class="niceButton3" href="/test/insert">用户插入测试</a>
            <a class="niceButton3" href="/user/add">注册</a>
            <a class="niceButton3" href="/user/login">登录</a>        
        </div>
    </div>
    
    <table>
    <thead>
        <tr>
          <th>用户名称</th>
          <th>用户密码</th>
          <th>用户电话</th>
          <th>用户年龄</th>
          <th>操作</th>
        </tr>
    </thead>
            {% for i in rw_list%}
                <tr>
                <td>{{i.user_name}}</td>
                <td>{{i.user_password}}</td>
                <td>{{i.user_number}}</td>
                <td>{{i.user_age}}</td>
                <td>
                <a class="niceButton2" href="http://127.0.0.1:8000/delete/?user_id={{i.user_id}}"style="text-decoration: none;">删除</a>
                </td>
                </tr>
            {% endfor %} 
    </table>
    <div>
</body>
</html>

webapp01/templates/welcome.html
{% load static %}
<!DOCTYPE html>
 <meta http-equiv="Cache-Control" content="max-age=7200" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>

    <h1 align="center">主页</h1>
        
    <div class="searchmain">
        <div class="searchcontainer">
            <form action="search1" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="搜索" class="search" name="search"><input type="submit" class="btnsearch" value="搜索">
        </div>
        <div class="login">
            <a class="niceButton3" href="/user/add">注册</a>
            <a class="niceButton3" href="/user/login">登录</a>        
        </div>
    </div>
    
    <table>
    <thead>
        <tr>
          <th>任务名称</th>
          <th>发布者</th>
          <th>发布日期</th>
          <th>截止日期</th>
          <th>操作</th>
        </tr>
    </thead>
            {% for i in rw_list%}
                <tr>
                <td>{{i.rw_name}}</td>
                <td>{{i.rw_fb_username}}</td>
                <td>{{i.rw_startdata}}</td>
                <td>{{i.rw_enddata}}</td>
                <td>
                <a class="niceButton2"href="http://{{ GLOBAL_IP }}:{{ GLOBAL_PORT }}/task_detail/?rw_id={{i.rw_id}}&login={{login}}" style="text-decoration: none;">详情</a>
                </td>
                </tr>
            {% endfor %} 
    </table>
    <div>
</html>